name : Build and Deploy

on:
  push:
    branches:
      - main
  pull:
    branches:
      - main

job:
  build:
    run-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
           node version: '20'
      - name: install Dependences
        uses: npm install
      - name: Build project
        uses: npm run build
      - name: Run Test
        uses: npm test
